#!/usr/bin/env sh

set -eux

cargo build \
    --target wasm32-unknown-unknown \
    --release
wasm-bindgen \
    --target web \
    --typescript \
    --out-dir static/pkg \
    --out-name index \
    ./target/wasm32-unknown-unknown/release/simple_rust_wasm.wasm
